apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
  namespace: ckad
spec:
  containers:
  - image: nginx:1.17.10
    name: pod1
    ports:
    - containerPort: 80
    resources: {}
    env:
    - name: DB_URL
      value: postgresql://mydb:5432
    - name: DB_USERNAME
      value: admin
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
