apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: complex-pod
  name: complex-pod
spec:
  initContainers:
  - image: busybox
    name: setup
    command: ['/bin/sh', '-c', 'wget -O- google.com']
  containers:
  - image: nginx:1.17-alpine
    name: complex-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
