apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: data-exchange
  name: data-exchange
spec:
  volumes:
  - name: logs
    emptyDir: {}
  containers:
  - image: busybox
    name: main-app
    resources: {}
    volumeMounts:
    - name: logs
      mountPath: /var/app/data
    command: ["/bin/sh", "-c", "counter=0; while true; do touch /var/app/data/$counter-data.txt; counter=$((counter+1)); sleep 30s; done;"]
  - image: busybox
    name: sidecar
    command: ["/bin/sh", "-c", "cd /var/app/data; while true; do ls | wc -l; sleep 60s; done;"]
    volumeMounts:
    - name: logs
      mountPath: /var/app/data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
