apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: security-context-demo
  name: security-context-demo
spec:
  containers:
  - image: alpine
    name: security-context-demo
    resources: {}
    securityContext:
      runAsUser: 1000
      capabilities:  
       add: ['CAP_SYS_TIME']
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
