apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp-pod
  name: temp-pod
spec:
  volumes:
  - name: vol
    emptyDir: {}
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: alpine:3.12.0
    name: container1
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /etc/a 
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: alpine:3.12.0
    name: container2
    volumeMounts:
    - name: vol
      mountPath: /etc/b
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
