apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  # This will re-write the url to remove the /video keyword before delegating the request
  # to `my-video-service` and get the 2nd segment value in the url and added to the path in backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "ckad-mock-exam-solution.com"
      http:
        paths:
          - path: "/video"
            pathType: Prefix
            backend:
              service:
                name: my-video-service
                port:
                  number: 8080
