apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: temp-pod-vol
  name: temp-pod-vol
spec:
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: logs-pvc
  containers:
  - image: nginx
    name: temp-pod-vol
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - name: vol
      mountPath: /var/log/nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
